metadata:
  annotations:
    app.openshift.io/connects-to: mock-t24-create-customer
  labels:
    app.kubernetes.io/component: Atomic
    app.kubernetes.io/part-of: Create-Customer
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: true  #Sidecar to istio
    spec:
     volumes:
        - name: kcb-truststore-pubcerts
          secret:
            secretName: kcb-truststore-pubcerts
            defaultMode: 420
     containers:
        - 
          volumeMounts:
            - name: kcb-truststore-pubcerts
              readOnly: true
              mountPath: /mnt/secrets
          resources:
            requests:
              cpu: 450m
              memory: 512Mi
            limits:
              cpu: 900m
              memory: 1024Mi
          env:
          - name: SPRING_APPLICATION_JSON
            value: '{"server":{"undertow":{"io-threads":1, "worker-threads":24}}}'
          - name: AMQP_PROTOCOL
            valueFrom:
              configMapKeyRef:
                name: configmap-create-customer
                key: amqp.protocol
          - name: AMQP_HOST
            valueFrom:
              configMapKeyRef:
                name: configmap-create-customer
                key: amqp.host
          - name: AMQP_PORT
            valueFrom:
              configMapKeyRef:
                name: configmap-create-customer
                key: amqp.port
          - name: AMQP_PARAMETERS
            value: transport.trustAll=true&transport.verifyHost=false&amqp.idleTimeout=120000
          - name: JAEGER_SERVICE_NAME
            value: t24-create-customer
          - name: JAEGER_SAMPLER_TYPE
            value: const
          - name: JAEGER_SAMPLER_PARAM
            value: 1
          - name: JAEGER_ENDPOINT
            value: http://jaeger-collector.istio-system.svc:14268/api/traces
          - name: JAEGER_PROPAGATION
            value: b3
          - name: JAEGER_REPORTER_LOG_SPANS
            value: "false"
          - name: T24_SERVICE_ENDPOINT_PORT
            valueFrom:
              configMapKeyRef:
                name: configmap-create-customer
                key: t24.service.endpoint.port
          - name: T24_SERVICE_ENDPOINT_PORT
            valueFrom:
              configMapKeyRef:
                name: configmap-create-customer
                key: t24.service.endpoint.port
          - name: T24_SERVICE_ENDPOINT_HOST
            valueFrom:
              configMapKeyRef:
                name: configmap-create-customer
                key: t24.service.endpoint.host
          - name: T24_SERVICE_ENDPOINT_SCHEME
            valueFrom:
              configMapKeyRef:
                name: configmap-create-customer
                key: t24.service.endpoint.scheme
          - name: T24_SERVICE_ENDPOINT_PATH
            valueFrom:
              configMapKeyRef:
                name: configmap-create-customer
                key: t24.service.endpoint.path
          - name: T24_SERVICE_ENDPOINT_TIMEOUT
            valueFrom:
              configMapKeyRef:
                name: configmap-create-customer
                key: t24.service.endpoint.timeout
          - name: VAULT_SERVICE_ENDPOINT_PORT
            valueFrom:
              configMapKeyRef:
                name: configmap-create-customer
                key: vault.service.endpoint.port
          - name: VAULT_SERVICE_ENDPOINT_HOST
            valueFrom:
              configMapKeyRef:
                name: configmap-create-customer
                key: vault.service.endpoint.host
          - name: VAULT_SERVICE_ENDPOINT_SCHEME
            valueFrom:
              configMapKeyRef:
                name: configmap-create-customer
                key: vault.service.endpoint.scheme
          - name: VAULT_SERVICE_ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: configmap-create-customer
                key: vault.service.environment
          - name: VAULT_SERVICE_ENDPOINT_TIMEOUT
            valueFrom:
              configMapKeyRef:
                name: configmap-create-customer
                key: vault.service.endpoint.timeout
          - name: TRUSTSTORE_PATH
            valueFrom:
              configMapKeyRef:
                name: configmap-create-customer
                key: truststore.path
          - name: TRUSTSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: kcb.truststore.pubcerts.password
                key: truststore.password         
                