apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: t24-create-customer
spec:
  scaleTargetRef:
    kind: DeploymentConfig
    name: t24-create-customer
    apiVersion: apps.openshift.io/v1
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50